/*OBS: CASO ALGUM SCRIPT NAO FUNCIONE, BASTA REMOVER OS COMENTARIOS*/
/*OBS: A CLAUSULA * SO SERÁ USADA NESSE PROJETO PARA ECONOMIZAR TEMPO, MAS VALE LEMBRAR QUE EM UM BANCO DE DADOS EMPRESARIAL NAO E ACONSELHAVEL USAR *, POIS PODE INTERFERIR NO DESEMPENHO DO BANCO DE DADOS*/

CREATE DATABASE EMPRESA;/*CRIAR BANCO EMPRESA*/

CREATE TABLE EMPRESA.CLIENTES/*CRIANDO TABELA CLIENTES DENTRO DO BANCO EMPRESA*/
(
	ID_CLIENTE INT,/*COLUNA DO TIPO INTEIRO*/
	NOME_CLIENTE VARCHAR(30) UNIQUE NOT NULL,/*COLUNA DO TIPO CARACTERE VARIAVEL, COM ATE 30 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	CPF VARCHAR(14) NOT NULL UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL COM ATE 14 CARACTERES, VALOR UNICO E NAO PODE SER NULO*/
	SEXO ENUM('M', 'F'),/*COLUNA DO TIPO ENUMERADA, ACEITANDO APENAS OS VALORES 'M' OU 'F'*/
	PAIS VARCHAR(30) DEFAULT 'Brasil',/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES, POR PADRAO DEVE VIR O DADO 'Brasil'*/
	UF VARCHAR(2),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 2 CARACTERES*/
	CIDADE VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	BAIRRO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	ENDERECO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	TEL_RES VARCHAR(19),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 19 CARACTERES*/
	TEL_CEL VARCHAR(19) UNIQUE/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 19 CARACTERES, VALOR UNICO(NAO SE REPETE)*/
);

CREATE TABLE EMPRESA.PRODUTOS/*CRIE A TABELA PRODUTOS DENTRO DO BANCO EMPRESA*/
(
	ID_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	NOME_PROD VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	MARCA VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	PRECO DECIMAL(10, 2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES, SENDO QUE 2 DELES DEVEM VIR DEPOIS DA VIRGULA*/
	COD_BARRAS VARCHAR(13) UNIQUE/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 13 CARACTERES, VALOR UNICO(NAO SE REPETE)*/
);

CREATE TABLE EMPRESA.VENDAS/*CRIANDO TABELA VENDAS DENTRO DO BANCO EMPRESA*/
(
	ID_VENDAS INT,/*COLUNA DO TIPO INTEIRO*/
	ID_VENDA_CLIENTE INT,/*COLUNA DO TIPO INTEIRO*/
	ID_VENDA_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	VALOR_DA_VENDA DECIMAL(10,2)/*COLUNA DO TIPO DECIMAL, ACEITANDO ATE 10 NUMEROS E TRAZENDO 2 DESTES NUMEROS DEPOIS DA VIRGULA*/
);

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.CLIENTES/*CLIENTES DENTRO DO BANCO EMPRESA*/
ADD/*ADICIONE*/
	CONSTRAINT PK_ID_CLIENTE PRIMARY KEY(ID_CLIENTE);/*RESTRICAO TORNANDO A COLUNA ID_CLIENTE UMA CHAVE PRIMARIA*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.PRODUTOS/*PRODUTOS DENTRO DO BANCO EMPRESA*/
ADD/*ADICIONE*/
	CONSTRAINT PK_ID_PROD PRIMARY KEY(ID_PROD);/*RESTRICAO TORNANDO A COLUNA ID_PROD UMA CHAVE PRIMARIA*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.VENDAS/*VENDAS DENTRO DO BANCO EMPRESA*/
ADD/*ADICIONE*/
	CONSTRAINT PK_ID_VENDAS PRIMARY KEY(ID_VENDAS);/*RESTRICAO TORNANDO A COLUNA ID_VENDAS UMA CHAVE PRIMARIA*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.CLIENTES/*CLIENTES DENTRO DO BANCO EMPRESA*/	 
MODIFY/*MODIFIQUE*/
	COLUMN ID_CLIENTE INT AUTO_INCREMENT;/*A COLUNA ID_CLIENTE TIPANDO COMO VALOR INTEIRO E AUTO INCREMENTAÇÃO*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.PRODUTOS/*PRODUTOS DENTRO DO BANCO EMPRESA*/
MODIFY/*MODIFIQUE*/
	COLUMN ID_PROD INT AUTO_INCREMENT;/*A COLUNA ID_PROD TIPANDO COMO VALOR INTEIRO E AUTO INCREMENTAÇÃO*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.VENDAS/*VENDAS DENTRO DO BANCO EMPRESA*/
MODIFY/*MODIFIQUE*/
	COLUMN ID_VENDAS INT AUTO_INCREMENT;/*A COLUNA ID_VENDAS TIPANDO COMO VALOR INTEIRO E AUTO INCREMENTAÇÃO*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.VENDAS/*VENDAS DENTRO DO BANCO EMPRESA*/
ADD/*ADICIONE*/
	CONSTRAINT FK_VENDAS_ID_VENDA_CLIENTES_REFERENCE_CLIENTES_ID_CLIENTE/*RESTRICAO*/
	FOREIGN KEY(ID_VENDA_CLIENTE)/*CHAVE ESTRANGEIRA COLUNA ID_VENDA_CLIENTE*/
	REFERENCES CLIENTES(ID_CLIENTE);/*FARA REFERENCIA A COLUNA ID_CLIENTE DA TABELA CLIENTES*/

ALTER TABLE/*ALTERE A TABELA*/
	EMPRESA.VENDAS/*VENDAS DENTRO DO BANCO EMPRESA*/
ADD/*ADICIONE*/
	CONSTRAINT FK_VENDAS_ID_VENDA_PROD_REFERENCES_PRODUTOS_ID_PROD/*RESTRICAO*/
	FOREIGN KEY(ID_VENDA_PROD)/*CHAVE ESTRANGEIRA COLUNA ID_VENDA_PROD*/
	REFERENCES PRODUTOS(ID_PROD);/*FARA REFERENCIA A COLUNA ID_PROD DA TABELA PRODUTOS*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	INFORMATION_SCHEMA.TABLE_CONSTRAINTS/*TABELA TABLE_CONSTRAINTS QUE ESTA DENTRO DO BANCO INFORMATION_SCHEMA*/
WHERE/*ONDE*/
	/*A COLUNA CONSTRAINT_NAME POSSUI O DADO FK_VENDAS_ID_VENDA_CLIENTES_REFERENCE_CLIENTES_ID_CLIENTE*/
	CONSTRAINT_NAME = 'FK_VENDAS_ID_VENDA_CLIENTES_REFERENCE_CLIENTES_ID_CLIENTE'
	OR/*OU*/
	/*A COLUNA CONSTRAINT_NAME POSSUI O DADO FK_VENDAS_ID_VENDA_PROD_REFERENCES_PRODUTOS_ID_PROD*/
	CONSTRAINT_NAME = 'FK_VENDAS_ID_VENDA_PROD_REFERENCES_PRODUTOS_ID_PROD';

CREATE DATABASE EMPRESA_BKP;/*CRIE O BANCO EMPRESA_BKP*/

CREATE TABLE EMPRESA_BKP.DADOS_INSERIDOS_CLIENTES/*CRIE A TABELA DADOS_INSERIDOS_CLIENTES DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_CLIENTE INT NOT NULL,/*COLUNA DO TIPO INTEIRO E NAO PODE SER NULO*/
	NOME_CLIENTE VARCHAR(30) UNIQUE NOT NULL,/*COLUNA DO TIPO CARACTERE VARIAVEL COM ATE 30 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	CPF VARCHAR(14) NOT NULL UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL COM ATE 14 CARACTERES, VALOR UNICO E NAO PODE SER NULO*/
	SEXO ENUM('M', 'F'),/*COLUNA DO TIPO ENUMERADA, ACEITANDO APENAS OS VALORES 'M' OU 'F'*/
	PAIS VARCHAR(30) DEFAULT 'Brasil',/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES, POR PADRAO DEVE VIR O DADO 'Brasil'*/
	UF VARCHAR(2),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 2 CARACTERES*/
	CIDADE VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	BAIRRO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	ENDERECO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 30 CARACTERES*/
	TEL_RES VARCHAR(19),/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 19 CARACTERES*/
	TEL_CEL VARCHAR(19) UNIQUE/*COLUNA DO TIPO CARACTERE VARIAVEL, ACEITANDO ATE 19 CARACTERES E VALOR UNICO(NAO SE REPETE)*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_CLIENTES_INSERIDOS/*CRIE A TRIGGER BKP_CLIENTES_INSERIDOS DENTRO DO BANCO EMPRESA*/
AFTER/*DEPOIS*/
INSERT/*DA INSERCAOT*/
	ON CLIENTES/*SOBRE A TABELA CLIENTES*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSERCAO DENTRO DE*/
	EMPRESA_BKP.DADOS_INSERIDOS_CLIENTES/*TABELA DADOS_INSERIDOS_CLIENTES QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*DOS VALORES*/
	(
		NULL,/*VALOR NULO*/
		NEW.ID_CLIENTE,/*NOVO VALOR DA COLUNA*/
		NEW.NOME_CLIENTE,/*NOVO VALOR DA COLUNA*/
		NEW.CPF,/*NOVO VALOR DA COLUNA*/
		NEW.SEXO,/*NOVO VALOR DA COLUNA*/
		NEW.PAIS,/*NOVO VALOR DA COLUNA*/
		NEW.UF,/*NOVO VALOR DA COLUNA*/
		NEW.CIDADE,/*NOVO VALOR DA COLUNA*/
		NEW.BAIRRO,/*NOVO VALOR DA COLUNA*/
		NEW.ENDERECO,/*NOVO VALOR DA COLUNA*/
		NEW.TEL_RES,/*NOVO VALOR DA COLUNA*/
		NEW.TEL_CEL/*NOVO VALOR DA COLUNA*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_INSERIDOS_PRODUTOS/*CRIE A TABELA DADOS_INSERIDOS_PRODUTOS DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	NOME_PROD VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	MARCA VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	PRECO DECIMAL(10,2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES, SENDO QUE 2 DELES DEVEM VIR DEPOIS DA VIRGULA*/
	COD_BARRAS VARCHAR(13) UNIQUE/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 13 CARACTERES E VALOR UNICO(NAO SE REPETE)*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_PRODUTOS_INSERIDOS/*CRIE A TRIGGER BKP_PRODUTOS_INSERIDOS DENTRO DO BANCO EMPRESA*/
AFTER/*DEPOIS*/
INSERT/*DA INSERCAO*/
	ON PRODUTOS/*SOBRE A TABELA PRODUTOS*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	EMPRESA_BKP.DADOS_INSERIDOS_PRODUTOS/*TABELA DADOS_INSERIDOS_PRODUTOS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		NEW.ID_PROD,/*NOVO VALOR DA COLUNA*/
		NEW.NOME_PROD,/*NOVO VALOR DA COLUNA*/
		NEW.MARCA,/*NOVO VALOR DA COLUNA*/
		NEW.PRECO,/*NOVO VALOR DA COLUNA*/
		NEW.COD_BARRAS/*NOVO VALOR DA COLUNA*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_INSERIDOS_VENDAS/*CRIE A TABELA DADOS_INSERIDOS_VENDAS DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_VENDAS INT,/*COLUNA DO TIPO INTEIRO*/
	ID_VENDA_CLIENTE INT,/*COLUNA DO TIPO INTEIRO*/
	ID_VENDA_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	VALOR_DA_VENDA DECIMAL/*COLUNA DO TIPO DECIMAL*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_VENDAS_INSERIDOS/*CRIE A TRIGGER BKP_VENDAS_INSERIDOS DENTRO DO BANCO EMRPESA*/
AFTER/*DEPOIS*/
INSERT/*DA INSERCAO*/
	ON VENDAS/*SOBRE A TABELA VENDAS*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSERCAO DENTRO DE*/
	EMPRESA_BKP.DADOS_INSERIDOS_VENDAS/*TABELA DADOS_INSERIDOS_VENDAS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*DOS VALORES*/
	(
		NULL,/*VALOR NULO*/
		NEW.ID_VENDAS,/*NOVO VALOR DA COLUNA*/
		NEW.ID_VENDA_CLIENTE,/*NOVO VALOR DA COLUNA*/
		NEW.ID_VENDA_PROD,/*NOVO VALOR DA COLUNA*/
		NEW.VALOR_DA_VENDA/*NOVO VALOR DA COLUNA*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_DELETADOS_CLIENTES/*CRIE A TABELA DADOS_DELETADOS_CLIENTES DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_CLIENTE INT NOT NULL,/*COLUNA DO TIPO INTEIRO E NAO PODE SER NULO*/
	NOME_CLIENTE VARCHAR(30) UNIQUE NOT NULL,/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	CPF VARCHAR(14) NOT NULL UNIQUE,/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 14 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	SEXO ENUM('M', 'F'),/*COLUNA DO TIPO ENUMERADA QUE ACEITA APENAS DOIS VALORES, SAO ESTES 'M' OU 'F'*/
	PAIS VARCHAR(30) DEFAULT 'Brasil',/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES, VALOR POR PADRAO E 'Brasil'*/
	UF VARCHAR(2),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 2 CARACTERES*/
	CIDADE VARCHAR(30),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	BAIRRO VARCHAR(30),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	ENDERECO VARCHAR(30),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	TEL_RES VARCHAR(19),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 19 CARACTERES*/
	TEL_CEL VARCHAR(19) UNIQUE/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 19 CARACTERES E VALOR UNICO(NAO SE REPETE)*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_CLIENTES_DELETADOS/*CRIE A TRIGGER BKP_CLIENTES_DELETADOS DENTRO DO BANCO EMPRESA*/
BEFORE/*ANTES*/
DELETE/*DE DELETAR*/
	ON CLIENTES/*SOBRE A TABELA CLIENTES*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	EMPRESA_BKP.DADOS_DELETADOS_CLIENTES/*TABELA DADOS_DELETADOS_CLIENTES QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		OLD.ID_CLIENTE,/*ANTIGO VALOR DA COLUNA*/
		OLD.NOME_CLIENTE,/*ANTIGO VALOR DA COLUNA*/
		OLD.CPF,/*ANTIGO VALOR DA COLUNA*/
		OLD.SEXO,/*ANTIGO VALOR DA COLUNA*/
		OLD.PAIS,/*ANTIGO VALOR DA COLUNA*/
		OLD.UF,/*ANTIGO VALOR DA COLUNA*/
		OLD.CIDADE,/*ANTIGO VALOR DA COLUNA*/
		OLD.BAIRRO,/*ANTIGO VALOR DA COLUNA*/
		OLD.ENDERECO,/*ANTIGO VALOR DA COLUNA*/
		OLD.TEL_RES,/*ANTIGO VALOR DA COLUNA*/
		OLD.TEL_CEL/*ANTIGO VALOR DA COLUNA*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_DELETADOS_PRODUTOS/*CRIE A TABELA DADOS_DELETADOS_PRODUTOS DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/	
	ID_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	NOME_PROD VARCHAR(30),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	MARCA VARCHAR(30),/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
	PRECO DECIMAL(10,2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES SENDO QUE 2 DELES DEVEM VIR DEPOIS DA VIRGULA*/
	COD_BARRAS VARCHAR(13) UNIQUE/*COLUNA DO TIPO CARACATERE VARIAVEL, PERMITINDO ATE 13 CARACTERES, VALOR UNICO(NAO SE REPETE)*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_PRODUTOS_DELETADOS/*CRIE A TRIGGER BKP_PRODUTOS_DELETADOS DENTRO DO BANCO EMPRESA*/
BEFORE/*ANTES*/
DELETE/*DE DELETAR*/
ON PRODUTOS/*SOBRE A TABELA PRODUTOS*/
FOR EACH ROW/*PARA CADA LINHA*/
BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	EMPRESA_BKP.DADOS_DELETADOS_PRODUTOS/*TABELA DADOS_DELETADOS_PRODUTOS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		OLD.ID_PROD,/*ANTIGO VALOR DA COLUNA*/
		OLD.NOME_PROD,/*ANTIGO VALOR DA COLUNA*/
		OLD.MARCA,/*ANTIGO VALOR DA COLUNA*/
		OLD.PRECO,/*ANTIGO VALOR DA COLUNA*/
		OLD.COD_BARRAS/*ANTIGO VALOR DA COLUNA*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_DELETADOS_VENDAS/*CRIE A TABELA DADOS_DELETADOS_VENDAS DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_VENDAS INT,/*COLUNA DO TIPO INTEIRO*/
	ID_VENDA_CLIENTE INT,/*COLUNA DO TIPO INTEIRO*/
	ID_VENDA_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	VALOR_DA_VENDA DECIMAL(10,2)/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES SENDO QUE 2 DELES DEVEM VIR DEPOIS DA VIRGULA*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_VENDAS_DELETADOS/*CRIE A TRIGGER BKP_VENDAS_DELETADOS DENTRO DO BANCO EMPRESA*/
BEFORE/*ANTES*/
DELETE/*DE DELETAR*/
ON VENDAS/*SOBRE A TABELA VENDAS*/
FOR EACH ROW/*PARA CADA LINHA*/
BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	EMPRESA_BKP.DADOS_DELETADOS_VENDAS/*TABELA DADOS_DELETADOS_VENDAS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		OLD.ID_VENDAS,/*ANTIGO VALOR DA COLUNA*/
		OLD.ID_VENDA_CLIENTE,/*ANTIGO VALOR DA COLUNA*/
		OLD.ID_VENDA_PROD,/*ANTIGO VALOR DA COLUNA*/
		OLD.VALOR_DA_VENDA/*ANTIGO VALOR DA COLUNA*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_ATUALIZADOS_CLIENTES/*CRIE A TABELA DADOS_ATUALIZADOS_CLIENTES DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_CLIENTE INT NOT NULL,/*COLUNA DO TIPO INTEIRO E NAO PODE SER NULO*/
	ANTIGO_NOME_CLIENTE VARCHAR(30) UNIQUE NOT NULL,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	NOVO_NOME_CLIENTE VARCHAR(30) UNIQUE NOT NULL,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	ANTIGO_CPF VARCHAR(14) NOT NULL UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 14 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	NOVO_CPF VARCHAR(14) NOT NULL UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 14 CARACTERES, VALOR UNICO(NAO SE REPETE) E NAO PODE SER NULO*/
	ANTIGO_SEXO ENUM('M', 'F'),/*COLUNA DO TIPO ENUMERADA, PERMITINDO APENAS DOIS VALORES,SAO ESTES 'M' OU 'F'*/
	NOVO_SEXO ENUM('M', 'F'),/*COLUNA DO TIPO ENUMERADA, PERMITINDO APENAS DOIS VALORES,SAO ESTES 'M' OU 'F'*/
	ANTIGO_PAIS VARCHAR(30) DEFAULT 'Brasil',/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES E O VALOR PADRAO DEVE SER 'Brasil'*/
	NOVO_PAIS VARCHAR(30) DEFAULT 'Brasil',/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES E O VALOR PADRAO DEVE SER 'Brasil'*/
	ANTIGO_UF VARCHAR(2),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 2 CARACTERES*/
	NOVO_UF VARCHAR(2),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 2 CARACTERES*/
	ANTIGO_CIDADE VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	NOVO_CIDADE VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	ANTIGO_BAIRRO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	NOVO_BAIRRO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	ANTIGO_ENDERECO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	NOVO_ENDERECO VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	ANTIGO_TEL_RES VARCHAR(19),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 19 CARACTERES*/
	NOVO_TEL_RES VARCHAR(19),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 19 CARACTERES*/
	ANTIGO_TEL_CEL VARCHAR(19) UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 19 CARACTERES E VALOR UNICO(NAO SE REPETE)*/
	NOVO_TEL_CEL VARCHAR(19) UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 19 CARACTERES E VALOR UNICO(NAO SE REPETE)*/
	DATA_HORA_ATUALIZACAO DATETIME,/*COLUNA DO TIPO DATA E HORA*/
	QUEM_ATUALIZOU VARCHAR(30)/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_CLIENTES_ATUALIZADOS/*CRIE A TRIGGER BKP_CLIENTES_ATUALIZADOS DENTRO DO BANCO EMPRESA*/
AFTER/*DEPOIS*/
UPDATE/*DA ATUALIZACAO*/
	ON CLIENTES/*SOBRE A TABELA CLIENTES*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	EMPRESA_BKP.DADOS_ATUALIZADOS_CLIENTES/*INSERCAO DENTRO DA TABELA DADOS_ATUALIZADOS_CLIENTES QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		OLD.ID_CLIENTE,/*ANTIGO VALOR DA COLUNA*/
		OLD.NOME_CLIENTE,/*ANTIGO VALOR DA COLUNA*/
		NEW.NOME_CLIENTE,/*NOVO VALOR DA COLUNA*/
		OLD.CPF,/*ANTIGO VALOR DA COLUNA*/
		NEW.CPF,/*NOVO VALOR DA COLUNA*/
		OLD.SEXO,/*ANTIGO VALOR DA COLUNA*/
		NEW.SEXO,/*NOVO VALOR DA COLUNA*/
		OLD.PAIS,/*ANTIGO VALOR DA COLUNA*/
		NEW.PAIS,/*NOVO VALOR DA COLUNA*/
		OLD.UF,/*ANTIGO VALOR DA COLUNA*/
		NEW.UF,/*NOVO VALOR DA COLUNA*/
		OLD.CIDADE,/*ANTIGO VALOR DA COLUNA*/
		NEW.CIDADE,/*NOVO VALOR DA COLUNA*/
		OLD.BAIRRO,/*ANTIGO VALOR DA COLUNA*/
		NEW.BAIRRO,/*NOVO VALOR DA COLUNA*/
		OLD.ENDERECO,/*ANTIGO VALOR DA COLUNA*/
		NEW.ENDERECO,/*NOVO VALOR DA COLUNA*/
		OLD.TEL_RES,/*ANTIGO VALOR DA COLUNA*/
		NEW.TEL_RES,/*NOVO VALOR DA COLUNA*/
		OLD.TEL_CEL,/*ANTIGO VALOR DA COLUNA*/
		NEW.TEL_CEL,/*NOVO VALOR DA COLUNA*/
		NOW(),/*DATA E HORA*/
		CURRENT_USER()/*USUARIO ATUAL/NOME DO USUARIO*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_ATUALIZADOS_PRODUTOS/*CRIE A TABELA DADOS_ATUALIZADOS_PRODUTOS DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	ANTIGO_NOME_PROD VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	NOVO_NOME_PROD VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	ANTIGO_MARCA VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	NOVO_MARCA VARCHAR(30),/*COLUNA DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	ANTIGO_PRECO DECIMAL(10,2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES, SENDO QUE 2 DELES DEVEM VIR DEPOIS DA VIRGULA*/
	NOVO_PRECO DECIMAL(10,2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES, SENDO QUE 2 DELES DEVEM VIR DEPOIS DA VIRGULA*/
	ANTIGO_COD_BARRAS VARCHAR(13) UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 13 CARACTERES E VALOR UNICO(NAO SE REPETE)*/
	NOVO_COD_BARRAS VARCHAR(13) UNIQUE,/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 13 CARACTERES E VALOR UNICO(NAO SE REPETE)*/	
	DATA_HORA_ATUALIZACAO DATETIME,/*COLUNA DO TIPO DATA E HORA*/
	QUEM_ATUALIZOU VARCHAR(30)/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_PRODUTOS_ATUALIZADOS/*CRIE A TRIGGER BKP_PRODUTOS_ATUALIZADOS DENTRO DO BANCO EMPRESA*/
AFTER/*DEPOIS*/
UPDATE/*DE ATUALIZAR*/
	ON PRODUTOS/*SOBRE A TABELA PRODUTOS*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	EMPRESA_BKP.DADOS_ATUALIZADOS_PRODUTOS/*TABELA DADOS_ATUALIZADOS_PRODUTOS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		OLD.ID_PROD,/*ANTIGO VALOR DA COLUNA*/
		OLD.NOME_PROD,/*ANTIGO VALOR DA COLUNA*/
		NEW.NOME_PROD,/*NOVO VALOR DA COLUNA*/
		OLD.MARCA,/*ANTIGO VALOR DA COLUNA*/
		NEW.MARCA,/*NOVO VALOR DA COLUNA*/
		OLD.PRECO,/*ANTIGO VALOR DA COLUNA*/
		NEW.PRECO,/*NOVO VALOR DA COLUNA*/
		OLD.COD_BARRAS,/*ANTIGO VALOR DA COLUNA*/
		NEW.COD_BARRAS,/*NOVO VALOR DA COLUNA*/
		NOW(),/*DATA E HORA ATUAL*/
		CURRENT_USER()/*USUARIO ATUAL/NOME DO USUARIO*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

CREATE TABLE EMPRESA_BKP.DADOS_ATUALIZADOS_VENDAS/*CRIE A TABELA DADOS_ATUALIZADOS_VENDAS DENTRO DO BANCO EMPRESA_BKP*/
(
	ID INT PRIMARY KEY AUTO_INCREMENT,/*COLUNA DO TIPO INTEIRO, CHAVE PRIMARIA E AUTO INCREMENTADA*/
	ID_VENDAS INT,/*COLUNA DO TIPO INTEIRO*/
	ANTIGO_ID_VENDA_CLIENTE INT,/*COLUNA DO TIPO INTEIRO*/
	NOVO_ID_VENDA_CLIENTE INT,/*COLUNA DO TIPO INTEIRO*/
	ANTIGO_ID_VENDA_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	NOVO_ID_VENDA_PROD INT,/*COLUNA DO TIPO INTEIRO*/
	ANTIGO_VALOR_DA_VENDA DECIMAL(10,2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES, SENDO QUE 2 DELES VEM DEPOIS DA VIRGULA*/
	NOVO_VALOR_DA_VENDA DECIMAL(10,2),/*COLUNA DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES, SENDO QUE 2 DELES VEM DEPOIS DA VIRGULA*/
	DATA_HORA_ATUALIZACAO DATETIME,/*COLUNA DO TIPO DATA E HORA*/
	QUEM_ATUALIZOU VARCHAR(30)/*COLUNA DO TIPO CARACTERE VARIAVEL, PERMITINDO ATE 30 CARACTERES*/
);

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE TRIGGER EMPRESA.BKP_VENDAS_ATUALIZADOS/*CRIE A TRIGGER BKP_VENDAS_ATUALIZADOS DENTRO DO BANCO EMPRESA*/
AFTER/*DEPOIS*/
UPDATE/*DE ATUALIZAR */
	ON VENDAS/*SOBRE A TABELA VENDAS*/
	FOR EACH ROW/*PARA CADA LINHA*/
	BEGIN/*INICIE*/
INSERT INTO/*INSERCAO DENTRO DE*/
	EMPRESA_BKP.DADOS_ATUALIZADOS_VENDAS/*TABELA DADOS_ATUALIZADOS_VENDAS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		NEW.ID_VENDAS,/*NOVO VALOR DA COLUNA*/
		OLD.ID_VENDA_CLIENTE,/*ANTIGO VALOR DA COLUNA*/
		NEW.ID_VENDA_CLIENTE,/*NOVO VALOR DA COLUNA*/
		OLD.ID_VENDA_PROD,/*ANTIGO VALOR DA COLUNA*/
		NEW.ID_VENDA_PROD,/*NOVO VALOR DA COLUNA*/
		OLD.VALOR_DA_VENDA,/*ANTIGO VALOR DA COLUNA*/
		NEW.VALOR_DA_VENDA,/*NOVO VALOR DA COLUNA*/
		NOW(),/*DATA E HORA ATUAL*/
		CURRENT_USER()/*USUARIO ATUAL/NOME DO USUARIO*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE PROCEDURE EMPRESA.INSERT_TAB_CLIENTES/*CRIE O PROCEDIMENTO INSERT_TAB_CLIENTES DENTRO DO BANCO EMPRESA*/
(
	NOME_CLIENTE VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	CPF VARCHAR(14),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 14 CARACTERES*/
	SEXO ENUM('M', 'F'),/*PARAMETRO DO TIPO ENUMERADA E PERMITINDO APENAS 2 CARACTERES, SENDO ESTES 'M' OU 'F'*/
	PAIS VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	UF VARCHAR(2),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 2 CARACTERES*/
	CIDADE VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	BAIRRO VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	ENDERECO VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	TEL_RES VARCHAR(19),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 19 CARACTERES*/
	TEL_CEL VARCHAR(19/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 19 CARACTERES*/
) 
BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	CLIENTES/*TABELA CLIENTES*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR*/
		NOME_CLIENTE,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		CPF,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		SEXO,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		PAIS,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		UF,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		CIDADE,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		BAIRRO,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		ENDERECO,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		TEL_RES,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		TEL_CEL/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'CAIO ALMEIDA MELO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'123.965.445-41',/*VALOR PARA OCUPAR O PARAMETRO*/
	'M',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ANAPOLIS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ANAPOLIM',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 12 QUADRA 2',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)3293-4418',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99714-4574'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'LUCAS ALFREDO MELO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'456.965.445-42',/*VALOR PARA OCUPAR O PARAMETRO*/
	'M',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ANAPOLIS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ANAPOLIM',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 12 QUADRA 3',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)3697-4477',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99999-4574'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'MARIA JUSSARA PINTO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'789.965.445-43',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'MA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'CAJARI',/*VALOR PARA OCUPAR O PARAMETRO*/
	'CAJADOS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 5 QUADRA 2',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)3737-4778',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99778-7884'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'MARLOM JOSE DA CRUZ',/*VALOR PARA OCUPAR O PARAMETRO*/
	'101.965.445-44',/*VALOR PARA OCUPAR O PARAMETRO*/
	'M',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'MA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'AÇAILANDIA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'CAMPINA SERRA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 12 QUADRA 25',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)4040-4418',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99663-4563'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'JUSSARA DIVINA SOUZA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'211.965.445-45',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'MT',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ANAPOLIS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BOM BAIRRO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 1 QUADRA 2',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)4545-4418',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99696-4576'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'MOISES PAULO SILVA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'311.965.485-46',/*VALOR PARA OCUPAR O PARAMETRO*/
	'M',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ABAIRA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'DOCE AXE',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 9 QUADRA 7',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)4511-1010',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99665-1121'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'MARIO JOSE DA COSTA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'312.165.445-47',/*VALOR PARA OCUPAR O PARAMETRO*/
	'M',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ADUSTINA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GELTIL SILVA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 7 QUADRA 7',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)3111-1515',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99714-1113'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'ROSA SANTOS SOARES',/*VALOR PARA OCUPAR O PARAMETRO*/
	'313.265.445-48',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'SC',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ABDON BATISTA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'MAGALHADO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 22 QUADRA 23',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)3939-4747',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99898-4574'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'LARISSA PAULA GUEDES',/*VALOR PARA OCUPAR O PARAMETRO*/
	'314.365.445-49',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'MG',/*VALOR PARA OCUPAR O PARAMETRO*/
	'ABREUS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'CAMPINAS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA FINIM QUADRA 2',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)4574-3918',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)99097-4664'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'PRISCILA DA COSTA NUNES',/*VALOR PARA OCUPAR O PARAMETRO*/
	'992.965.445-44',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BELGICA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BX',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRUXELAS',/*VALOR PARA OCUPAR O PARAMETRO*/
	'NODES',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA JULIO ALMEDIDA QUADRA 8',/*VALOR PARA OCUPAR O PARAMETRO*/
	NULL,/*VALOR*/
	'+55(62)99636-4888'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'ARLINDA CRUZ COELHO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'128.875.145-99',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GOIANIA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'JARDIM VITORIA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 4 QUADRA 2',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)4315-3918',/*VALOR PARA OCUPAR O PARAMETRO*/
	'+55(62)98455-1111'/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_CLIENTES/*CHAMANDO PROCEDURE*/
(
	'AMANDA NUNES BARBOSA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'888.915.433-30',/*VALOR PARA OCUPAR O PARAMETRO*/
	'F',/*VALOR PARA OCUPAR O PARAMETRO*/
	'BRASIL',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'GOIANIA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'JARDIM ABREU',/*VALOR PARA OCUPAR O PARAMETRO*/
	'RUA 4 QUADRA 5',/*VALOR PARA OCUPAR O PARAMETRO*/
	NULL,/*VALOR*/
	'+55(62)98787-4861'/*VALOR PARA OCUPAR O PARAMETRO*/
);

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.CLIENTES;/*TABELA CLIENTES DENTRO DO BANCO EMPRESA*/

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE PROCEDURE EMPRESA.INSERT_TAB_PRODUTOS/*CRIE O PROCEDIMENTO INSERT_TAB_PRODUTOS DENTRO DO BANCO EMPRESA*/
(
	NOME_PROD VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	MARCA VARCHAR(30),/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 30 CARACTERES*/
	PRECO DECIMAL(10,2),/*PARAMETRO DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES SENDO QUE 2 DEVEM VIR DEPOIS DA VIRGULA*/
	COD_BARRAS VARCHAR(13)/*PARAMETRO DO TIPO CARACTERE VARIAVEL E PERMITINDO ATE 13 CARACTERES*/
) 
BEGIN/*INICIE*/
INSERT INTO/*INSIRA DENTRO DE*/
	PRODUTOS/*TABELA PRODUTOS*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR*/
		NOME_PROD,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		MARCA,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		PRECO,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		COD_BARRAS/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'POCCO X3 PRO',/*VALOR PARA OCUPAR O PARAMETRO*/
	'XIAOMI',/*VALOR PARA OCUPAR O PARAMETRO*/
	1400.00,/*VALOR PARA OCUPAR O PARAMETRO*/
	784512454547/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'GALAXY Z FLIP4',/*VALOR PARA OCUPAR O PARAMETRO*/
 	'SAMSUNG',/*VALOR PARA OCUPAR O PARAMETRO*/
 	 2145.00,/*VALOR PARA OCUPAR O PARAMETRO*/
 	 123123456784/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'P26',/*VALOR PARA OCUPAR O PARAMETRO*/
	'POSITIVO',/*VALOR PARA OCUPAR O PARAMETRO*/
	75.30,/*VALOR PARA OCUPAR O PARAMETRO*/
	451478965233/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'S22 ULTRA',/*VALOR PARA OCUPAR O PARAMETRO*/
	'POSITIVO',/*VALOR PARA OCUPAR O PARAMETRO*/
	602.99,/*VALOR PARA OCUPAR O PARAMETRO*/
	47895656523/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'IPHONE 13 PRO MAX',/*VALOR PARA OCUPAR O PARAMETRO*/
	'APPLE',/*VALOR PARA OCUPAR O PARAMETRO*/
	8999.90,/*VALOR PARA OCUPAR O PARAMETRO*/
	315896547831/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'C20',/*VALOR PARA OCUPAR O PARAMETRO*/
	'NOKIA',/*VALOR PARA OCUPAR O PARAMETRO*/
	573.00,/*VALOR PARA OCUPAR O PARAMETRO*/
	789444475454/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'UP PLAY',/*VALOR PARA OCUPAR O PARAMETRO*/
	'MULTILASER',/*VALOR PARA OCUPAR O PARAMETRO*/
	94.00,/*VALOR PARA OCUPAR O PARAMETRO*/
	741526487777/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'HUAWEI X8 SILVER',/*VALOR PARA OCUPAR O PARAMETRO*/
	'HONOR',/*VALOR PARA OCUPAR O PARAMETRO*/
	1330.12,/*VALOR PARA OCUPAR O PARAMETRO*/
	321452145784/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'LG K61',/*VALOR PARA OCUPAR O PARAMETRO*/
	'LG',/*VALOR PARA OCUPAR O PARAMETRO*/
	1249.00,/*VALOR PARA OCUPAR O PARAMETRO*/
	741256353535/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_PRODUTOS/*CHAMANDO PROCEDURE*/
(
	'LG K52',/*VALOR PARA OCUPAR O PARAMETRO*/
	'LG',/*VALOR PARA OCUPAR O PARAMETRO*/
	989.90,/*VALOR PARA OCUPAR O PARAMETRO*/
	745896565652/*VALOR PARA OCUPAR O PARAMETRO*/
);

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.PRODUTOS;/*TABELA PRODUTOS DENTRO DO BANCO EMPRESA*/

DELIMITER $/*ALTERANDO DELIMITADOR*/
CREATE PROCEDURE EMPRESA.INSERT_TAB_VENDAS/*CRIE O PROCEDIMENTO INSERT_TAB_VENDAS DENTRO DO BANCO EMPRESA*/
(
	ID_VENDA_CLIENTE INT,/*PARAMETRO DO TIPO INTEIRO*/
	ID_VENDA_PROD INT,/*PARAMETRO DO TIPO INTEIRO*/
	VALOR_DA_VENDA DECIMAL(10,2)/*PARAMETRO DO TIPO DECIMAL, PERMITINDO ATE 10 CARACTERES SENDO QUE 2 DEVEM VIR DEPOIS DA VIRGULA*/
) 
BEGIN/*INICIE*/
INSERT INTO/*INSERCAO DENTRO DE*/
	VENDAS/*TABELA VENDAS*/
VALUES/*OS VALORES*/
	(
		NULL,/*VALOR NULO*/
		ID_VENDA_CLIENTE,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		ID_VENDA_PROD,/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
		VALOR_DA_VENDA/*PARAMETRO QUE IRA RECEBER UM VALOR NA CHAMADA DA PROCEDURE*/
	);
END/*FIM*/
$/*ENCERRANDO COM DELIMITADOR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	1,/*VALOR PARA OCUPAR O PARAMETRO*/
	2,/*VALOR PARA OCUPAR O PARAMETRO*/
	2145.00/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	2,/*VALOR PARA OCUPAR O PARAMETRO*/
	3,/*VALOR PARA OCUPAR O PARAMETRO*/
	75.30/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	3,/*VALOR PARA OCUPAR O PARAMETRO*/
	3,/*VALOR PARA OCUPAR O PARAMETRO*/
	75.30/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	4,/*VALOR PARA OCUPAR O PARAMETRO*/
	3,/*VALOR PARA OCUPAR O PARAMETRO*/
	75.30/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	5,/*VALOR PARA OCUPAR O PARAMETRO*/
 	4,/*VALOR PARA OCUPAR O PARAMETRO*/
 	602.99/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	6,/*VALOR PARA OCUPAR O PARAMETRO*/
	5,/*VALOR PARA OCUPAR O PARAMETRO*/
	8999.90/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	7,/*VALOR PARA OCUPAR O PARAMETRO*/
	6,/*VALOR PARA OCUPAR O PARAMETRO*/
	573.00/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	8,/*VALOR PARA OCUPAR O PARAMETRO*/
	7,/*VALOR PARA OCUPAR O PARAMETRO*/
	94.00/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	9,/*VALOR PARA OCUPAR O PARAMETRO*/
	8,/*VALOR PARA OCUPAR O PARAMETRO*/
	1330.12/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	10,/*VALOR PARA OCUPAR O PARAMETRO*/
	9,/*VALOR PARA OCUPAR O PARAMETRO*/
	1249.00/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	10,/*VALOR PARA OCUPAR O PARAMETRO*/
	1,/*VALOR PARA OCUPAR O PARAMETRO*/
	1400.00/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	10,/*VALOR PARA OCUPAR O PARAMETRO*/
	2,/*VALOR PARA OCUPAR O PARAMETRO*/
	2145.00/*VALOR PARA OCUPAR O PARAMETRO*/
);

CALL INSERT_TAB_VENDAS/*CHAMANDO PROCEDURE*/
(
	10,/*VALOR PARA OCUPAR O PARAMETRO*/
	4,/*VALOR PARA OCUPAR O PARAMETRO*/
	602.99/*VALOR PARA OCUPAR O PARAMETRO*/
);

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.VENDAS;/*TABELA VENDAS DENTRO DO BANCO EMPRESA*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_INSERIDOS_CLIENTES;/*TABELA DADOS_INSERIDOS_CLIENTES DENTRO DO BANCO EMPRESA_BKP*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_INSERIDOS_PRODUTOS;/*TABELA DADOS_INSERIDOS_PRODUTOS DENTRO DO BANCO EMPRESA_BKP*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_INSERIDOS_VENDAS;/*TABELA DADOS_INSERIDOS_VENDAS DENTRO DO BANCO EMPRESA_BKP*/

/*SE FOR DELETAR UM CLIENTE E O MESMO ESTIVER COLIGADO A ALGUMA VENDA NA TABELA VENDAS, PRIMEIRO E NECESSARIO DELETAR ESSE CLIENTE DA TABELA VENDAS PARA DEPOIS DELETAR ESSE CLIENTE DA TABELA CLIENTES*/

/*SE FOR DELETAR UM PRODUTO E O MESMO ESTIVER COLIGADO A ALGUMA VENDA NA TABELA VENDAS, PRIMEIRO E NECESSARIO DELETAR ESSE PRODUTO DA TABELA VENDAS PARA DEPOIS DELETAR ESSE PRODUTO DA TABELA PRODUTOS*/

DELETE FROM/*DELETE DENTRO DE*/
	EMPRESA.VENDAS/*TABELA VENDAS QUE FICA DENTRO DO BANCO EMPRESA*/
WHERE/*ONDE*/
	ID_VENDAS BETWEEN 1 AND 6;/*COLUNA ID_VENDAS TENHA O VALOR ENTRE 1 E 6*/

DELETE FROM/*DELETE DENTRO DE*/
	EMPRESA.PRODUTOS/*TABELA PRODUTOS QUE FICA DENTRO DO BANCO EMPRESA*/
WHERE/*ONDE*/
	ID_PROD = 3;/*ID_PROD SEJA IGUAL A 3*/

DELETE FROM/*DELETE DENTRO DE*/
	EMPRESA.CLIENTES/*TABELA CLIENTES QUE FICA DENTRO DO BANCO EMPRESA*/
WHERE/*ONDE*/
	ID_CLIENTE = 1;/*ID_CLIENTE E IGUAL A 1*/

SELECT/*SELECIONE*/
	*/*TUDO*/ 
FROM /*DENTRO DE*/
	EMPRESA.CLIENTES;/*TABELA CLIENTES DENTRO DO BANCO EMPRESA*/

SELECT/*SELECIONE*/ 
	*/*TUDO*/ 
FROM/*DENTRO DE*/
	EMPRESA.PRODUTOS;/*TABELA PRODUTOS DENTRO DO BANCO EMPRESA*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.VENDAS;/*TABELA VENDAS DENTRO DO BANCO EMPRESA*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_DELETADOS_CLIENTES;/*TABELA DADOS_DELETADOS_CLIENTES QUE FICA DENTRO DO BANCO EMPRESA_BKP*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_DELETADOS_PRODUTOS;/*TABELA DADOS_DELETADOS_PRODUTOS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_DELETADOS_VENDAS;/*TABELA DADOS_DELETADOS_VENDAS QUE FICA DENTRO DO BANCO EMPRESA_BKP*/

UPDATE/*ATUALIZE*/
	EMPRESA.CLIENTES/*TABELA CLIENTES QUE FICA DENTRO DO BANCO EMPRESA*/
SET/*SETANDO*/
	NOME_CLIENTE = 'JULIA BONITA',/*COLUNA = VALOR*/
	CPF = '741.963.852-87',/*COLUNA = VALOR*/
	SEXO = 'F',/*COLUNA = VALOR*/
	PAIS = 'HONDURAS',/*COLUNA = VALOR*/
	UF = 'DF',/*COLUNA = VALOR*/
	CIDADE = 'TAGUATINGA',/*COLUNA = VALOR*/
	BAIRRO = 'TAGUATINGA NORTE',/*COLUNA = VALOR*/
	ENDERECO = 'QD 2 LT 5',/*COLUNA = VALOR*/
	TEL_RES = '+55(62)3369-4417',/*COLUNA = VALOR*/
	TEL_CEL = '+55(61)99798-7847'/*COLUNA = VALOR*/
WHERE/*ONDE*/
	ID_CLIENTE = 2;/*ID_CLIENTE E IGUAL A 2*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_ATUALIZADOS_CLIENTES;/*TABELA DADOS_ATUALIZADOS_CLIENTES DENTRO DO BANCO EMPRESA_BKP*/

UPDATE/*ATUALIZE*/
	EMPRESA.PRODUTOS/*TABELA PRODUTOS DENTRO DO BANCO EMPRESA*/
SET/*SETANDO*/
	NOME_PROD = 'POCCO X4 PRO',/*COLUNA = VALOR*/
	MARCA = 'XIAOMI EVOLUTION',/*COLUNA = VALOR*/
	PRECO = 1600.00,/*COLUNA = VALOR*/
	COD_BARRAS = 745214523652/*COLUNA = VALOR*/
WHERE/*ONDE*/
	ID_PROD = 2;/*ONDE O ID_PROD E IGUAL A 2*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_ATUALIZADOS_PRODUTOS;/*TABELA DADOS_ATUALIZADOS_PRODUTOS DENTRO DO BANCO EMPRESA_BKP*/

UPDATE/*ATUALIZAR*/
	EMPRESA.VENDAS/*TABELA VENDAS DENTRO DO BANCO EMPRESA*/
SET/*SETANDO*/
	ID_VENDA_CLIENTE = 2,/*COLUNA = VALOR*/
	ID_VENDA_PROD = 1,/*COLUNA = VALOR*/
	VALOR_DA_VENDA = 1400.00/*COLUNA = VALOR*/
WHERE/*ONDE*/
	ID_VENDAS = 7;/*O ID_VENDAS E IGUAL A 7*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA_BKP.DADOS_ATUALIZADOS_VENDAS;/*TABELA DADOS_ATUALIZADOS_VENDAS DENTRO DO BANCO EMPRESA_BKP*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW REL_VENDAS AS/*CRIE A VIEW REL_VENDAS*/
SELECT/*SELECIONE*/
	V.ID_VENDAS,/*COLUNA ID_VENDAS DENTRO DA TABELA VENDAS*/
	C.NOME_CLIENTE,/*COLUNA NOME_CLIENTE DENTRO DA TABELA CLIENTES*/
	P.NOME_PROD,/*COLUNA NOME_PROD DENTRO DA TABELA PRODUTOS*/
	V.VALOR_DA_VENDA/*COLUNA VALOR_DA_VENDA DENTRO DA TABELA VENDAS*/
FROM/*DENTRO DE*/
	VENDAS V/*TABELA VENDAS APELIDADA COMO V*/
	INNER JOIN CLIENTES C/*JUNCAO INTERNA DA TABELA CLIENTES APELIDADA COMO C*/
	ON V.ID_VENDA_CLIENTE = C.ID_CLIENTE/*SOBRE O VALOR DA COLUNA ID_VENDA_CLIENTE(DENTRO DA TABELA VENDAS) SENDO IGUAL AO VALOR DA COLUNA ID_CLIENTE(DENTRO DA TABELA CLIENTES)*/
	INNER JOIN PRODUTOS P/*JUNCAO INTERNA DA TABELA PRODUTOS APELIDADA COMO P*/
	ON V.ID_VENDA_PROD = P.ID_PROD/*SOBRE O VALOR DA COLUNA ID_VENDA_PROD(DENTRO DA TABELA VENDAS) SENDO IGUAL AO VALOR DA COLUNA ID_PROD(DENTRO DA TABELA PRODUTOS)*/
ORDER BY/*ORDENAR POR*/
	V.ID_VENDAS;/*COLUNA ID_VENDAS DENTRO DA TABELA VENDAS*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.REL_VENDAS;/*VIEW REL_VENDAS QUE ESTA DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETANDO SELECAO*/
	'ID_VENDAS',
	'NOME_CLIENTE',
	'NOME_PROD',
	'VALOR_DA_VENDA'
UNION ALL/*UNINDO TODAS*/
SELECT/*SELECIONE AS COLUNAS*/
	ID_VENDAS,
	NOME_CLIENTE,
	NOME_PROD,
	VALOR_DA_VENDA
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.REL_VENDAS.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	LINES TERMINATED BY '\n'/*LINHAS TERMINADAS POR*/
FROM/*DENTRO DE*/
	EMPRESA.REL_VENDAS;/*VIEW REL_VENDAS DENTRO DO BANCO EMPRESA*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW EMPRESA.CALC_REL_VENDAS AS/*CRIE A VIEW CALC_REL_VENDAS DENTRO DO BANCO EMPRESA COMO*/
SELECT/*SELECIONE*/
	CEILING(SUM(VALOR_DA_VENDA))/*ARREDONDAMENTO DA SOMA DA COLUNA VALOR_DA_VENDA*/
	AS "VALOR TOTAL VENDAS",/*COMO*/
	CEILING(AVG(VALOR_DA_VENDA))/*ARREDONDAMENTO DA MEDIA DA COLUNA VALOR_DA_VENDA*/
	AS "MEDIA VALOR TOTAL VENDAS",/*COMO*/
	MAX(VALOR_DA_VENDA)/*VALOR MAXIMO DA COLUNA VALOR_DA_VENDA*/
	AS "PRECO MAXIMO VENDAS",/*COMO*/
	MIN(VALOR_DA_VENDA)/*VALOR MINIMO DA COLUNA VALOR_DA_VENDA*/
	AS "PRECO MINIMO VENDAS",/*COMO*/
	MAX(VALOR_DA_VENDA) - MIN(VALOR_DA_VENDA)/*VALOR MAXIMO DIMINUIDO PELO VALOR MINIMO DA COLUNA VALOR_DA_VENDA*/
	AS "AMPLIT.TOTAL",/*COMO*/
	ROUND(STDDEV_POP(VALOR_DA_VENDA))/*ARREDONDAMENTO DO DESVIO PADRAO DA COLUNA VALOR_DA_VENDA*/
	AS "DESV.PADRAO",/*COMO*/
	ROUND(VAR_POP(VALOR_DA_VENDA),2)/*ARREDONDAMENTO DA VARIANCIA DA COLUNA VALOR_DA_VENDA TRAZENDO 2 NUMEROS DEPOIS DA VIRGULA*/
	AS "VARIANCIA",/*COMO*/
	ROUND(/*ARREDONDAMENTO DO RESULTADO*/
		(STDDEV_POP(VALOR_DA_VENDA) / AVG(VALOR_DA_VENDA)) * 100,/*DESVIO PADRAO DA COLUNA DIVIDIDO PELA MEDIA DA COLUNA MULTIPLICADO POR 100)*/
		2/*TRAZENDO 2 NUMEROS DEPOIS DA VIRGULA*/
	)
	AS "COEF.VARIACAO",/*COMO*/
	COUNT(ID_VENDAS)/*CONTAGEM DE QUANTOS DADOS TEM A COLUNA ID_VENDAS*/
	AS "QTD.VENDAS"/*COMO*/
FROM/*DENTRO DE*/
	REL_VENDAS;/*VIEW*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.CALC_REL_VENDAS;/*VIEW CALC_REL_VENDAS DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETE A SELECAO*/
	'VALOR TOTAL VENDAS',
	'MEDIA VALOR TOTAL VENDAS',
	'PRECO MAXIMO VENDAS',
	'PRECO MINIMO VENDAS',
	'AMPLIT.TOTAL',
	'DESV.PADRAO',
	'VARIANCIA',
	'COEF.VARIACAO',
	'QTD.VENDAS'
UNION ALL/*UNIAO DE TODOS*/
SELECT/*SELECIONE AS COLUNAS*/
	`VALOR TOTAL VENDAS`,
	`MEDIA VALOR TOTAL VENDAS`,
	`PRECO MAXIMO VENDAS`,
	`PRECO MINIMO VENDAS`,
	`AMPLIT.TOTAL`,
	`DESV.PADRAO`,
	`VARIANCIA`,
	`COEF.VARIACAO`,
	`QTD.VENDAS`
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.CALC_REL_VENDAS.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	LINES TERMINATED BY '\n'/*LINHAS TERMINADAS POR*/
FROM/*DENTRO DE*/
	EMPRESA.CALC_REL_VENDAS;/*VIEW CALC_REL_VENDAS DENTRO DO BANCO EMPRESA*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW RANKING_PROD_MAIS_VENDIDO/*CRIE A VIEW RANKING_PROD_MAIS_VENDIDO*/
AS/*COMO*/
SELECT/*SELECIONE*/
	COUNT(V.ID_VENDA_PROD)/*CONTAGEM DA COLUNA ID_VENDA_PROD DENTRO DA TABELA VENDAS*/
	AS "QUANTIDADE DE VEZES QUE O PROD FOI VENDIDO",/*COMO*/
	P.NOME_PROD/*COLUNA NOME_PROD DENTRO DA TABELA PRODUTOS*/
	AS "NOME DO PRODUTO",/*COMO*/
	P.PRECO/*COLUNA PRECO DENTRO DA TABELA PRODUTOS*/
FROM/*DENTRO DE*/
	VENDAS V/*TABELA VENDAS APELIDADA COMO V*/
	INNER JOIN PRODUTOS P/*JUNCAO INTERNA COM A TABELA PRODUTOS APELIDADA P*/
	ON V.ID_VENDA_PROD = P.ID_PROD/*SOBRE A COLUNA ID_VENDA_PROD(DENTRO DA TABELA VENDAS) SENDO IGUAL A COLUNA ID_PROD(DENTRO DA TABELA PRODUTOS)*/
GROUP BY/*AGRUPE POR*/
	ID_VENDA_PROD/*COLUNA*/
ORDER BY/*ORDENE POR*/
	COUNT(V.ID_VENDA_PROD)/*CONTAGEM DA COLUNA ID_VENDA_PROD DENTRO DA TABELA VENDAS*/
	DESC;/*DE FORMA DECRESCENTE*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.RANKING_PROD_MAIS_VENDIDO;/*VIEW RANKING_PROD_MAIS_VENDIDO DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETANDO SELECAO*/
	'QUANTIDADE DE VEZES QUE O PROD FOI VENDIDO',
	'NOME DO PRODUTO',
	'PRECO'
UNION ALL/*UNIAO DE TODOS*/
SELECT/*SELECIONE*/
	COUNT(V.ID_VENDA_PROD),/*CONTAGEM DA COLUNA ID_VENDA_PROD DENTRO DA TABELA VENDAS*/
	P.NOME_PROD,/*COLUNA NOME_PROD DENTRO DA TABELA PRODUTOS*/
	P.PRECO/*COLUNA PRECO DENTRO DA TABELA PRODUTOS*/
FROM/*DENTRO DE*/
	(
		SELECT/*SELECIONE*/
			ID_VENDA_PROD,/*COLUNA*/
			COUNT(ID_VENDA_PROD) AS QTD_VENDAS/*CONTAGEM DA COLUNA ID_VENDA_PROD COMO QTD_VENDAS*/
		FROM/*DENTRO DE*/
			VENDAS/*TABELA*/
		GROUP BY/*AGRUPADO POR*/
			ID_VENDA_PROD/*COLUNA*/
		ORDER BY/*ORDENE POR*/
			QTD_VENDAS DESC/*COLUNA DE FORMA DECRESCENTE*/
	) V/*TABELA TEMPORARIA NOMEADA COMO V*/
	INNER JOIN PRODUTOS P/*JUNCAO INTERNA DA TABELA PRODUTOS APELIDADA P*/
	ON V.ID_VENDA_PROD = P.ID_PROD/*SOBRE O VALOR DA COLUNA ID_VENDA_PROD(DENTRO DA TABELA VENDAS) SENDO IGUAL AO VALOR DA COLUNA ID_PROD(DENTRO DA TABELA PRODUTOS)*/
GROUP BY/*AGRUPE POR*/
	P.NOME_PROD,/*COLUNA NOME_PROD DENTRO DA TABELA PRODUTOS*/
	P.PRECO/*COLUNA P.PRECO DENTRO DA TABELA PRODUTOS*/
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.RANKING_PROD_MAIS_VENDIDO.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	LINES TERMINATED BY '\n';/*LINHAS TERMINADAS POR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW RANKING_CLIENTES_QUE_MAIS_COMPRARAM/*CRIE A VIEW RANKING_CLIENTES_QUE_MAIS_COMPRARAM*/
AS/*COMO*/
SELECT/*SELECIONE*/
	C.NOME_CLIENTE AS "NOME DO CLIENTE",/*COLUNA NOME_CLIENTE DENTRO DA TABELA CLIENTES COMO*/
	COUNT(*) AS "QUANTIDADE DE COMPRAS"/*CONTAGEM DE TUDO COMO*/
FROM/*DENTRO DE*/
	CLIENTES C/*TABELA CLIENTES APELIDADA COMO C*/
	JOIN VENDAS V/*JUNCAO DA TABELA VENDAS APELIDADA COMO V*/
	ON C.ID_CLIENTE = V.ID_VENDA_CLIENTE/*SOBRE A COLUNA ID_CLIENTE(DENTRO DA TABELA CLIENTES) SENDO IGUAL A COLUNA ID_VENDA_CLIENTE(DENTRO DA TABELA VENDAS)*/
GROUP BY/*AGRUPE POR*/
	C.ID_CLIENTE/*COLUNA ID_CLIENTE DENTRO DA TABELA CLIENTES*/
ORDER BY/*AGRUPE POR*/
	COUNT(*) DESC;/*CONTAGEM DE TUDO DE FORMA DECRESCENTE*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.RANKING_CLIENTES_QUE_MAIS_COMPRARAM;/*VIEW RANKING_CLIENTES_QUE_MAIS_COMPRARAM DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETANDO SELECAO*/
    'NOME DO CLIENTE',
    'QUANTIDADE DE COMPRAS'
UNION ALL/*UNIAO DE TODOS*/
SELECT/*SELECIONE*/
    */*TUDO*/
    INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.RANKING_CLIENTES_QUE_MAIS_COMPRARAM.csv'/*NO ARQUIVO DE SAIDA*/
    FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
    OPTIONALLY ENCLOSED BY '"'/*OPCIONALMENTE INCLUIDOS POR LINHAS*/
    LINES TERMINATED BY '\n'/*LINHAS TERMINADAS POR*/
FROM/*DENTRO DE*/
    EMPRESA.RANKING_CLIENTES_QUE_MAIS_COMPRARAM;/*VIEW RANKING_CLIENTES_QUE_MAIS_COMPRARAM DENTRO DO BANCO EMPRESA*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW QTD_CLIENTE_POR_REGIAO/*CRIE A VIEW QTD_CLIENTE_POR_REGIAO DENTRO DO BANCO EMPRESA*/
AS/*COMO*/
SELECT/*SELECIONE*/
	PAIS,/*COLUNA*/
	UF,/*COLUNA*/
	COUNT(*) AS "QUANTIDADE DE CLIENTES"/*CONTAGEM DE TUDO COMO*/
FROM/*DENTRO DE*/
	CLIENTES/*TABELA*/
GROUP BY/*AGRUPE POR*/
	PAIS,/*COLUNA*/
	UF/*COLUNA*/
ORDER BY/*ORDENE POR*/
	PAIS,/*COLUNA*/
	UF;/*COLUNA*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.QTD_CLIENTE_POR_REGIAO;/*TABELA QTD_CLIENTE_POR_REGIAO DENTRO DO BANCO EMPRESA*/

(
	SELECT/*PROJETANDO SELECAO*/
		'PAIS',
		'UF',
		'QUANTIDADE DE CLIENTES'
)
UNION ALL/*UNIAO DE TODOS*/
(
	SELECT/*SELECIONE*/
		PAIS,/*COLUNA*/
		UF,/*COLUNA*/
		COUNT(*)/*CONTAGEM DE TUDO*/
	FROM/*DENTRO DE*/
		CLIENTES/*TABELA*/
	GROUP BY/*AGRUPE POR*/
		PAIS,/*COLUNA*/
		UF/*COLUNA*/
	ORDER BY/*ORDENE POR*/
		PAIS,/*COLUNA*/
		UF/*COLUNA*/
)
INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.QTD_CLIENTE_POR_REGIAO.csv'/*NO ARQUIVO DE SAIDA*/
FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
ENCLOSED BY '"'/*CERCADO POR*/
LINES TERMINATED BY '\n';/*LINHAS TERMINADAS POR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW PROD_PRECO_ABAIXO_IGUAL_A_MEDIA/*CRIE A VIEW PROD_PRECO_ABAIXO_IGUAL_A_MEDIA*/
AS/*COMO*/
SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	PRODUTOS/*TABELA*/
WHERE/*ONDE*/
	PRECO <=/*O PRECO SEJA MENOR OU IGUAL A*/
	(
		SELECT/*SELECIONE*/
			AVG(PRECO)/*MEDIA DA COLUNA PRECO*/
		FROM/*DENTRO*/
			PRODUTOS/*DA TABELA PRODUTOS*/
	)
ORDER BY/*ORDENE POR*/
	ID_PROD ASC;/*COLUNA ID_PROD DE FORMA CRESCENTE*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.PROD_PRECO_ABAIXO_IGUAL_A_MEDIA;/*VIEW PROD_PRECO_ABAIXO_IGUAL_A_MEDIA*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
SELECT/*PROJETE A SELECAO*/
	'ID_PROD',
	'NOME_PROD',
	'MARCA',
	'PRECO',
	'COD_BARRAS'
UNION ALL/*UNIAO DE TUDO*/
SELECT/*SELECIONE AS COLUNAS*/
	ID_PROD,
	NOME_PROD,
	MARCA,
	PRECO,
	COD_BARRAS
FROM/*DENTRO DE*/
	EMPRESA.PROD_PRECO_ABAIXO_IGUAL_A_MEDIA/*VIEW PROD_PRECO_ABAIXO_IGUAL_A_MEDIA QUE ESTA DENTRO DO BANCO EMPRESA*/
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.PRODUTOS_PRECO_ABAIXO_IGUAL_MEDIA.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	ENCLOSED BY '"'/*CERCADO POR*/
	LINES TERMINATED BY '\n';/*LINHAS TERMINADAS POR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/		
CREATE VIEW PROD_PRECO_ACIMA_DA_MEDIA/*CRIE A VIEW PROD_PRECO_ACIMA_DA_MEDIA DENTRO DO BANCO EMPRESA*/
AS/*COMO*/
SELECT/*SELECIONE*/	
	*/*TUDO*/
FROM/*DENTRO DE*/
	PRODUTOS/*DA TABELA PRODUTOS*/
WHERE/*ONDE*/
	PRECO >/*O PRECO E MAIOR QUE*/
	(
		SELECT/*SELECIONE*/
			AVG(PRECO)/*MEDIA DA COLUNA PRECO*/
		FROM/*DENTRO DE*/
			PRODUTOS/*TABELA*/
	)
ORDER BY/*ORDENE POR*/
	ID_PROD ASC;/*COLUNA DE FORMA CRESCENTE*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.PROD_PRECO_ACIMA_DA_MEDIA;/*VIEW PROD_PRECO_ACIMA_DA_MEDIA QUE ESTA DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETE A SELECAO*/
	'ID_PROD',
	'NOME_PROD',
	'MARCA',
	'PRECO',
	'COD_BARRAS'
UNION ALL/*UNIAO DE TODOS*/
SELECT/*SELECIONE AS COLUNAS*/
	ID_PROD,
	NOME_PROD,
	MARCA,
	PRECO,
	COD_BARRAS
FROM/*DENTRO DE*/
	EMPRESA.PROD_PRECO_ACIMA_DA_MEDIA/*VIEW PROD_PRECO_ACIMA_DA_MEDIA QUE ESTA DENTRO DO BANCO EMPRESA*/
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.PROD_PRECO_ACIMA_MEDIA.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	ENCLOSED BY '"'/*CERCADO POR*/
	LINES TERMINATED BY '\n';/*LINHAS TERMINADAS POR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ABAIXO_IGUAL_MD/*CRIE A VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ABAIXO_IGUAL_MD*/ 
AS/*COMO*/
SELECT/*SELECIONE*/
	V.ID_VENDAS,/*COLUNA ID_VENDAS DENTRO DA TABELA VENDAS*/
	C.NOME_CLIENTE AS "CLIENTE",/*COLUNA NOME_CLIENTE DENTRO DA TABELA CLIENTES COMO "CLIENTE"*/
	P.NOME_PROD AS "PRODUTO",/*COLUNA NOME_PROD DENTRO DA TABELA PRODUTOS COMO "PRODUTO"*/
	P.PRECO/*COLUNA PRECO DENTRO DA TABELA PRODUTOS*/
FROM/*DENTRO DE*/
	CLIENTES C/*TABELA CLIENTES APELIDADA COMO C*/
	JOIN VENDAS V/*JUNCAO COM A TABELA VENDAS APELIDADA COMO V*/
	ON V.ID_VENDA_CLIENTE = C.ID_CLIENTE/*SOBRE A COLUNA ID_VENDA_CLIENTE DENTRO DA TABELA VENDAS SENDO IGUAL A COLUNA ID_CLIENTE DENTRO DA TABELA CLIENTES*/
	JOIN PRODUTOS P/*JUNCAO COM A TABELA PRODUTOS APELIDADA COMO P*/
	ON P.ID_PROD = V.ID_VENDA_PROD/*SOBRE A COLUNA ID_PROD DENTRO DA TABELA PRODUTOS SENDO IGUAL A COLUNA ID_VENDA_PROD DENTRO DA TABELA VENDAS*/
WHERE/*ONDE*/
	P.PRECO <=/*COLUNA PRECO DENTRO DA TABELA PRODUTOS E MENOR OU IGUAL*/
	(
		SELECT/*SELECAO*/
			AVG(PRECO)/*MEDIA DA COLUNA PRECO*/
		FROM/*DENTRO DE*/
			PRODUTOS/*TABELA PRODUTOS*/
	)
ORDER BY/*ORDENE POR*/
	C.NOME_CLIENTE ASC;/*COLUNA NOME_CLIENTE DENTRO DA TABELA CLIENTES DE FORMA CRESCENTE*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.CLIENTES_QUE_COMPRARAM_PROD_PRECO_ABAIXO_IGUAL_MD;/*VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ABAIXO_IGUAL_MD QUE ESTA DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETANDO SELECAO*/
	'ID_VENDAS',
	'CLIENTE',
	'PRODUTO',
	'PRECO'
UNION ALL/*UNIAO DE TODOS*/
SELECT/*SELECIONE AS COLUNAS*/
	ID_VENDAS,
	CLIENTE,
	PRODUTO,
	PRECO
FROM/*DENTRO DE*/
	EMPRESA.CLIENTES_QUE_COMPRARAM_PROD_PRECO_ABAIXO_IGUAL_MD/*VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ABAIXO_IGUAL_MD QUE FICA DENTRO DO BANCO EMPRESA*/
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.CLIENTES_COMPRARAM_PRECO_ABAIXO_MEDIA.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	ENCLOSED BY '"'/*CERCADO POR*/
	LINES TERMINATED BY '\n';/*LINHAS TERMINADAS POR*/

USE EMPRESA;/*USE O BANCO EMPRESA*/
CREATE VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD/*CRIE A VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD*/
AS/*COMO*/
SELECT/*SELECIONE*/
	V.ID_VENDAS,/*COLUNA ID_VENDAS DENTRO DA TABELA VENDAS*/
	C.NOME_CLIENTE AS "CLIENTE",/*COLUNA NOME_CLIENTE DENTRO DA TABELA CLIENTES COMO "CLIENTE"*/
	P.NOME_PROD AS "PRODUTO",/*COLUNA NOME_PROD DENTRO DA TABELA PRODUTOS COMO "PRODUTO"*/
	P.PRECO/*COLUNA PRECO DENTRO DA TABELA PRODUTOS*/	
FROM/*DENTRO DE*/
	CLIENTES C/*TABELA CLIENTES APELIDADA COMO C*/
	JOIN VENDAS V/*JUNCAO COM A TABELA VENDAS APELIDADA COMO V*/
	ON V.ID_VENDA_CLIENTE = C.ID_CLIENTE/*SOBRE A COLUNA ID_VENDA_CLIENTE(DENTRO DA TABELA VENDAS) SENDO IGUAL A COLUNA ID_CLIENTE DENTRO DA TABELA CLIENTES*/
	JOIN PRODUTOS P/*JUNCAO COM A TABELA PRODUTOS APELIDADA COMO P*/
	ON P.ID_PROD = V.ID_VENDA_PROD/*SOBRE A COLUNA ID_PROD(DENTRO DA TABELA PRODUTOS) SENDO IGUAL A COLUNA ID_VENDA_PROD DENTRO DA TABELA VENDAS*/
WHERE/*ONDE*/
	P.PRECO >/*COLUNA PRECO DENTRO DA TABELA PRODUTOS SEJA MAIOR*/ 
	(
		SELECT/*SELECIONE*/
			AVG(PRECO)/*MEDIA DA COLUNA PRECO*/
		FROM/*DENTRO DE*/
			PRODUTOS/*TABELA*/
	)
ORDER BY/*ORDENE POR*/
	C.NOME_CLIENTE ASC;/*VIEW NOME_CLIENTE DENTRO DA TABELA CLIENTES DE FORMA CRESCENTE*/

SELECT/*SELECIONE*/
	*/*TUDO*/
FROM/*DENTRO DE*/
	EMPRESA.CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD;/*VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD DENTRO DO BANCO EMPRESA*/

SELECT/*PROJETANDO SELECAO*/
	'ID_VENDAS',
	'CLIENTE',
	'PRODUTO',
	'PRECO'
UNION ALL/*UNIAO DE TODOS*/
SELECT/*SELECIONE AS COLUNAS*/
	ID_VENDAS,
	CLIENTE,
	PRODUTO,
	PRECO
FROM/*DENTRO DE*/
	EMPRESA.CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD/*DENTRO DA VIEW CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD QUE FICA DENTRO DO BANCO EMPRESA*/
	INTO OUTFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/EMPRESA.CLIENTES_QUE_COMPRARAM_PROD_PRECO_ACIMA_MD.csv'/*NO ARQUIVO DE SAIDA*/
	FIELDS TERMINATED BY ';'/*CAMPOS TERMINADOS POR*/
	ENCLOSED BY '"'/*CERCADO POR*/
	LINES TERMINATED BY '\n';/*LINHAS TERMINADAS POR*/